package com.helphi.question.dao;

import com.datastax.oss.driver.api.mapper.annotations.DaoFactory;
import com.datastax.oss.driver.api.mapper.annotations.DaoKeyspace;
import com.datastax.oss.driver.api.mapper.annotations.Mapper;

/** Mapper for dao interfaces. Classes are autogenerated at build time*/
@Mapper
public interface QuestionMapper {

    @DaoFactory
    QuestionDao questionDao(@DaoKeyspace String keyspace);
}
